printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: all
bracketSpacing: true
arrowParens: 'avoid'
proseWrap: never
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: false
endOfLine: auto
overrides:
  - files: '*.md'
    options:
      tabWidth: 2
  - files: '*.nvue'
    options:
      parser: 'vue'
